export const COLLECTIONS = {
  STAFF: 'staff',
  MEMBERS: 'members',
  CREATIVE_ARTS: 'creative_arts',
  CAMPUSES: 'campuses',
  SCHOOLS: 'schools',
  ATTENDANCE: 'attendance',
  OFFERINGS: 'offerings',
  EVENTS: 'events',
  TRANSPORT: 'transport',
  TRANSPORT_ASSIGNMENTS: 'transportAssignments',
  DEVELOPMENT_TASKS: 'developmentTasks',
  TASKS: 'tasks',
  NOTIFICATIONS: 'notifications',
  MINISTRIES: 'ministries',
  SERVICE_PROGRAMS: 'servicePrograms',
  TRAVEL_DESTINATIONS: 'travelDestinations',
  MACHANEH_MOVIES: 'machanehMovies',
};
